/*
Copyright (c) 2003-2008 Terence Parr. All rights reserved.
Code licensed under the BSD License:
http://www.antlr.org/license.html

Some parts of the ANTLR class:
Copyright (c) 2008, Yahoo! Inc. All rights reserved.
Code licensed under the BSD License:
http://developer.yahoo.net/yui/license.txt
*/
if("undefined"==typeof org||!org)var org={};if("undefined"==typeof org.antlr||!org.antlr)org.antlr={runtime:{tree:{}}};org.antlr.global=function(){return GLOBAL||this}.call(null);org.antlr.namespace=function(){var a=arguments,b=null,c,d,e;for(c=0;c<a.length;c+=1){e=a[c].split(".");b=org.antlr.global;for(d=0;d<e.length;d+=1)b[e[d]]=b[e[d]]||{},b=b[e[d]]}return b};org.antlr.env=org.antlr.env||{};
org.antlr.env.ua=function(){var a={ie:0,opera:0,gecko:0,webkit:0,mobile:null,air:0,rhino:!1},b,c;try{b=navigator.userAgent;/KHTML/.test(b)&&(a.webkit=1);if((c=b.match(/AppleWebKit\/([^\s]*)/))&&c[1]){a.webkit=parseFloat(c[1]);if(/ Mobile\//.test(b))a.mobile="Apple";else if(c=b.match(/NokiaN[^\/]*/))a.mobile=c[0];if(c=b.match(/AdobeAIR\/([^\s]*)/))a.air=c[0]}if(!a.webkit)if((c=b.match(/Opera[\s\/]([^\s]*)/))&&c[1]){if(a.opera=parseFloat(c[1]),c=b.match(/Opera Mini[^;]*/))a.mobile=c[0]}else if((c=b.match(/MSIE\s([^;]*)/))&&
c[1])a.ie=parseFloat(c[1]);else if(c=b.match(/Gecko\/([^\s]*)/))if(a.gecko=1,(c=b.match(/rv:([^\s\)]*)/))&&c[1])a.gecko=parseFloat(c[1])}catch(d){}try{"undefined"==typeof window&&"undefined"!=typeof loadClass&&(a.rhino=!0)}catch(e){}return a}();org.antlr.namespace("org.antlr.runtime.tree");
org.antlr.lang=org.antlr.lang||{isArray:function(a){if(a){var b=org.antlr.lang;return b.isNumber(a.length)&&b.isFunction(a.splice)}return!1},isBoolean:function(a){return"boolean"===typeof a},isFunction:function(a){return"function"===typeof a},isNull:function(a){return null===a},isNumber:function(a){return"number"===typeof a&&isFinite(a)},isObject:function(a){return a&&("object"===typeof a||org.antlr.lang.isFunction(a))||!1},isString:function(a){return"string"===typeof a},isUndefined:function(a){return"undefined"===
typeof a},_IEEnumFix:function(a,b){if(org.antlr.env.ua.ie){var c=["toString","valueOf"],d;for(d=0;d<c.length;d+=1){var e=c[d],f=b[e];org.antlr.lang.isFunction(f)&&f!=Object.prototype[e]&&(a[e]=f)}}},extend:function(a,b,c){if(!b||!a)throw Error("org.antlr.lang.extend failed, please check that all dependencies are included.");var d=function(){};d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;a.superclass=b.prototype;b.prototype.constructor==Object.prototype.constructor&&(b.prototype.constructor=
b);if(c){for(var e in c)a.prototype[e]=c[e];org.antlr.lang._IEEnumFix(a.prototype,c)}},augmentObject:function(a,b){if(!b||!a)throw Error("Absorb failed, verify dependencies.");var c=arguments,d,e=c[2];if(e&&!0!==e)for(d=2;d<c.length;d+=1)a[c[d]]=b[c[d]];else{for(d in b)if(e||!a[d])a[d]=b[d];org.antlr.lang._IEEnumFix(a,b)}},augmentProto:function(a,b){if(!b||!a)throw Error("Augment failed, verify dependencies.");for(var c=[a.prototype,b.prototype],d=2;d<arguments.length;d+=1)c.push(arguments[d]);org.antlr.lang.augmentObject.apply(this,
c)},merge:function(){for(var a={},b=arguments,c=0,d=b.length;c<d;c+=1)org.antlr.lang.augmentObject(a,b[c],!0);return a},isValue:function(a){var b=org.antlr.lang;return b.isObject(a)||b.isString(a)||b.isNumber(a)||b.isBoolean(a)},array:{peek:function(a){if(!org.antlr.lang.isArray(a))throw Error("org.antlr.lang.array.peek: a is not an array.");var b=a.length;if(0>=b)throw Error("org.antlr.lang.array.peek: a is empty.");return a[b-1]}}};
org.antlr.runtime.RecognizerSharedState=function(){this.following=[];this._fsp=-1;this.errorRecovery=!1;this.lastErrorIndex=-1;this.failed=!1;this.backtracking=this.syntaxErrors=0;this.token=this.ruleMemo=null;this.tokenStartCharIndex=-1;this.text=null};org.antlr.runtime.IndexOutOfBoundsException=function(a){org.antlr.runtime.IndexOutOfBoundsException.superclass.constructor.call(this,a)};org.antlr.lang.extend(org.antlr.runtime.IndexOutOfBoundsException,Error,{name:"org.antlr.runtime.IndexOutOfBoundsException"});
org.antlr.runtime.RecognitionException=function(a){org.antlr.runtime.RecognitionException.superclass.constructor.call(this);this.input=a;this.index=a.index();a instanceof org.antlr.runtime.TokenStream&&(this.token=a.LT(1),this.line=this.token.getLine(),this.charPositionInLine=this.token.getCharPositionInLine());a instanceof org.antlr.runtime.tree.TreeNodeStream?this.extractInformationFromTreeNodeStream(a):a instanceof org.antlr.runtime.CharStream?(this.c=a.LA(1),this.line=a.getLine(),this.charPositionInLine=
a.getCharPositionInLine()):this.c=a.LA(1);this.message=this.toString()};
org.antlr.lang.extend(org.antlr.runtime.RecognitionException,Error,{input:null,index:null,token:null,node:null,c:null,line:null,name:"org.antlr.runtime.RecognitionException",charPositionInLine:null,approximateLineInfo:null,extractInformationFromTreeNodeStream:function(a){var b,c,d;this.node=a.LT(1);c=a.getTreeAdaptor();if(d=c.getToken(this.node))if(this.token=d,0>=d.getLine()){d=-1;for(b=a.LT(d);b;){if((b=c.getToken(b))&&0<b.getLine()){this.line=b.getLine();this.charPositionInLine=b.getCharPositionInLine();
this.approximateLineInfo=!0;break}--d;b=a.LT(d)}}else this.line=d.getLine(),this.charPositionInLine=d.getCharPositionInLine();else this.node instanceof org.antlr.runtime.tree.Tree?(this.line=this.node.getLine(),this.charPositionInLine=this.node.getCharPositionInLine(),this.node instanceof org.antlr.runtime.tree.CommonTree&&(this.token=this.node.token)):(a=c.getType(this.node),c=c.getText(this.node),this.token=new org.antlr.runtime.CommonToken(a,c))},getUnexpectedType:function(){return this.input instanceof
org.antlr.runtime.TokenStream?this.token.getType():this.input instanceof org.antlr.runtime.tree.TreeNodeStream?this.input.getTreeAdaptor().getType(this.node):this.c}});org.antlr.runtime.MismatchedTokenException=function(a,b){0===arguments.length?this.expecting=org.antlr.runtime.Token.INVALID_TOKEN_TYPE:(org.antlr.runtime.MismatchedTokenException.superclass.constructor.call(this,b),this.expecting=a)};
org.antlr.lang.extend(org.antlr.runtime.MismatchedTokenException,org.antlr.runtime.RecognitionException,{toString:function(){return"MismatchedTokenException("+this.getUnexpectedType()+"!="+this.expecting+")"},name:"org.antlr.runtime.MismatchedTokenException"});org.antlr.runtime.UnwantedTokenException=function(a,b){0<arguments.length&&org.antlr.runtime.UnwantedTokenException.superclass.constructor.call(this,a,b)};
org.antlr.lang.extend(org.antlr.runtime.UnwantedTokenException,org.antlr.runtime.MismatchedTokenException,{getUnexpectedToken:function(){return this.token},toString:function(){var a=", expected "+this.expecting;this.expecting===org.antlr.runtime.Token.INVALID_TOKEN_TYPE&&(a="");return!org.antlr.lang.isValue(this.token)?"UnwantedTokenException(found="+a+")":"UnwantedTokenException(found="+this.token.getText()+a+")"},name:"org.antlr.runtime.UnwantedTokenException"});
org.antlr.runtime.MissingTokenException=function(a,b,c){0<arguments.length&&(org.antlr.runtime.MissingTokenException.superclass.constructor.call(this,a,b),this.inserted=c)};
org.antlr.lang.extend(org.antlr.runtime.MissingTokenException,org.antlr.runtime.MismatchedTokenException,{getMissingType:function(){return this.expecting},toString:function(){return org.antlr.lang.isValue(this.inserted)&&org.antlr.lang.isValue(this.token)?"MissingTokenException(inserted "+this.inserted+" at "+this.token.getText()+")":org.antlr.lang.isValue(this.token)?"MissingTokenException(at "+this.token.getText()+")":"MissingTokenException"},name:"org.antlr.runtime.MissingTokenException"});
org.antlr.runtime.NoViableAltException=function(a,b,c,d){org.antlr.runtime.NoViableAltException.superclass.constructor.call(this,d);this.grammarDecisionDescription=a;this.decisionNumber=b;this.stateNumber=c};
org.antlr.lang.extend(org.antlr.runtime.NoViableAltException,org.antlr.runtime.RecognitionException,{toString:function(){return this.input instanceof org.antlr.runtime.CharStream?"NoViableAltException('"+this.getUnexpectedType()+"'@["+this.grammarDecisionDescription+"])":"NoViableAltException("+this.getUnexpectedType()+"@["+this.grammarDecisionDescription+"])"},name:"org.antlr.runtime.NoViableAltException"});
org.antlr.runtime.EarlyExitException=function(a,b){org.antlr.runtime.EarlyExitException.superclass.constructor.call(this,b);this.decisionNumber=a};org.antlr.lang.extend(org.antlr.runtime.EarlyExitException,org.antlr.runtime.RecognitionException,{name:"org.antlr.runtime.EarlyExitException"});org.antlr.runtime.MismatchedSetException=function(a,b){org.antlr.runtime.MismatchedSetException.superclass.constructor.call(this,b);this.expecting=a};
org.antlr.lang.extend(org.antlr.runtime.MismatchedSetException,org.antlr.runtime.RecognitionException,{toString:function(){return"MismatchedSetException("+this.getUnexpectedType()+"!="+this.expecting+")"},name:"org.antlr.runtime.MismatchedSetException"});org.antlr.runtime.MismatchedNotSetException=function(a,b){org.antlr.runtime.MismatchedNotSetException.superclass.constructor.call(this,a,b)};
org.antlr.lang.extend(org.antlr.runtime.MismatchedNotSetException,org.antlr.runtime.MismatchedSetException,{toString:function(){return"MismatchedNotSetException("+this.getUnexpectedType()+"!="+this.expecting+")"},name:"org.antlr.runtime.MismatchedNotSetException"});org.antlr.runtime.MismatchedRangeException=function(a,b,c){if(0===arguments.length)return this;org.antlr.runtime.MismatchedRangeException.superclass.constructor.call(this,c);this.a=a;this.b=b};
org.antlr.lang.extend(org.antlr.runtime.MismatchedRangeException,org.antlr.runtime.RecognitionException,{toString:function(){return"MismatchedRangeException("+this.getUnexpectedType()+" not in ["+this.a+","+this.b+"])"},name:"org.antlr.runtime.MismatchedRangeException"});org.antlr.runtime.FailedPredicateException=function(a,b,c){org.antlr.runtime.FailedPredicateException.superclass.constructor.call(this,a);this.ruleName=b;this.predicateText=c};
org.antlr.lang.extend(org.antlr.runtime.FailedPredicateException,org.antlr.runtime.RecognitionException,{toString:function(){return"FailedPredicateException("+this.ruleName+",{"+this.predicateText+"}?)"},name:"org.antlr.runtime.FailedPredicateException"});org.antlr.runtime.BitSet=function(a){a||(a=org.antlr.runtime.BitSet.BITS);org.antlr.lang.isArray(a)?this.bits=a:org.antlr.lang.isNumber(a)&&(this.bits=[])};
org.antlr.lang.augmentObject(org.antlr.runtime.BitSet,{BITS:32,LOG_BITS:5,MOD_MASK:31,bitMask:function(a){return 1<<(a&org.antlr.runtime.BitSet.MOD_MASK)},numWordsToHold:function(a){return(a>>org.antlr.runtime.BitSet.LOG_BITS)+1},wordNumber:function(a){return a>>org.antlr.runtime.BitSet.LOG_BITS},of:function(a,b){var c,d,e;if(org.antlr.lang.isNumber(a)){if(org.antlr.lang.isNumber(b)){e=new org.antlr.runtime.BitSet(b+1);for(c=a;c<=b;c++)d=org.antlr.runtime.BitSet.wordNumber(c),e.bits[d]|=org.antlr.runtime.BitSet.bitMask(c)}else e=
new org.antlr.runtime.BitSet(a+1),e.add(a);return e}if(org.antlr.lang.isArray(a)){e=new org.antlr.runtime.BitSet;for(c=a.length-1;0<=c;c--)e.add(a[c]);return e}if(a instanceof org.antlr.runtime.BitSet)return!a?null:a;if(a instanceof org.antlr.runtime.IntervalSet){if(!a)return null;e=new org.antlr.runtime.BitSet;e.addAll(a);return e}if(org.antlr.lang.isObject(a)){d=[];for(c in a)org.antlr.lang.isNumber(c)&&d.push(c);return org.antlr.runtime.BitSet.of(d)}}});
org.antlr.runtime.BitSet.prototype={add:function(a){var b=org.antlr.runtime.BitSet.wordNumber(a);b>=this.bits.length&&this.growToInclude(a);this.bits[b]|=org.antlr.runtime.BitSet.bitMask(a)},addAll:function(a){var b,c;if(a instanceof org.antlr.runtime.BitSet)this.orInPlace(a);else if(!(a instanceof org.antlr.runtime.IntervalSet)&&org.antlr.lang.isArray(a))for(b=0;b<a.length;b++)c=a[b],this.add(c)},and:function(a){var b=this.clone();b.andInPlace(a);return b},andInPlace:function(a){var b=Math.min(this.bits.length,
a.bits.length),c;for(c=b-1;0<=c;c--)this.bits[c]&=a.bits[c];for(c=b;c<this.bits.length;c++)this.bits[c]=0},clear:function(a){if(0===arguments.length){var b;for(b=this.bits.length-1;0<=b;b--)this.bits[b]=0}else b=org.antlr.runtime.BitSet.wordNumber(a),b>=this.bits.length&&this.growToInclude(a),this.bits[b]&=~org.antlr.runtime.BitSet.bitMask(a)},clone:function(){var a,b,c=[];a=0;for(b=this.bits.length;a<b;a++)c[a]=this.bits[a];return new org.antlr.runtime.BitSet(c)},size:function(){var a=0,b,c,d;for(b=
this.bits.length-1;0<=b;b--)if(c=this.bits[b],0!==c)for(d=org.antlr.runtime.BitSet.BITS-1;0<=d;d--)0!==(c&1<<d)&&a++;return a},equals:function(a){if(!a||!(a instanceof org.antlr.runtime.BitSet))return!1;var b,c=Math.min(this.bits.length,a.bits.length);for(b=0;b<c;b++)if(this.bits[b]!=a.bits[b])return!1;if(this.bits.length>c)for(b=c+1;b<this.bits.length;b++){if(0!==this.bits[b])return!1}else if(a.bits.length>c)for(b=c+1;b<a.bits.length;b++)if(0!==a.bits[b])return!1;return!0},growToInclude:function(a){Math.max(this.bits.length<<
1,org.antlr.runtime.BitSet.numWordsToHold(a));var a=[],b,c;b=0;for(c=this.bits.length;b<c;b++)a[b]=this.bits[b];this.bits=a},member:function(a){var b=org.antlr.runtime.BitSet.wordNumber(a);return b>=this.bits.length?!1:0!==(this.bits[b]&org.antlr.runtime.BitSet.bitMask(a))},getSingleElement:function(){var a;for(a=0;a<this.bits.length<<org.antlr.runtime.BitSet.LOG_BITS;a++)if(this.member(a))return a;return-1},isNil:function(){var a;for(a=this.bits.length-1;0<=a;a--)if(0!==this.bits[a])return!1;return!0},
complement:function(a){if(a)return a.subtract(this);a=this.clone();a.notInPlace();return a},notInPlace:function(){var a,b,c;if(0===arguments.length)for(a=this.bits.length-1;0<=a;a--)this.bits[a]=~this.bits[a];else{1===arguments.length?(a=0,b=arguments[0]):(a=arguments[0],b=arguments[1]);for(this.growToInclude(b);a<=b;a++)c=org.antlr.runtime.BitSet.wordNumber(a),this.bits[c]^=org.antlr.runtime.BitSet.bitMask(a)}},or:function(a){if(!a)return this;var b=this.clone();b.orInPlace(a);return b},orInPlace:function(a){if(a){a.bits.length>
this.bits.length&&this.setSize(a.bits.length);var b;for(b=Math.min(this.bits.length,a.bits.length)-1;0<=b;b--)this.bits[b]|=a.bits[b]}},remove:function(a){var b=org.antlr.runtime.BitSet.wordNumber(a);b>=this.bits.length&&this.growToInclude(a);this.bits[b]&=~org.antlr.runtime.BitSet.bitMask(a)},setSize:function(a){for(a-=this.bits.length;0<=a;)this.bits.push(0),a--},numBits:function(){return this.bits.length<<org.antlr.runtime.BitSet.LOG_BITS},lengthInLongWords:function(){return this.bits.length},
subset:function(a){return!a?!1:this.and(a).equals(this)},subtractInPlace:function(a){if(a){var b;for(b=0;b<this.bits.length&&b<a.bits.length;b++)this.bits[b]&=~a.bits[b]}},subtract:function(a){if(!a||!(a instanceof org.antlr.runtime.BitSet))return null;var b=this.clone();b.subtractInPlace(a);return b},toArray:function(){var a=[],b,c=0;for(b=0;b<this.bits.length<<org.antlr.runtime.BitSet.LOG_BITS;b++)this.member(b)&&(a[c++]=b);return a},toPackedArray:function(){return this.bits},toString:function(){return 0===
arguments.length?this.toString1(null):org.antlr.lang.isString(arguments[0])?org.antlr.lang.isValue(arguments[1])?this.toString2(arguments[0],arguments[1]):this.toString1(null):this.toString1(arguments[0])},toString1:function(a){var b="{",c,d=!1;for(c=0;c<this.bits.length<<org.antlr.runtime.BitSet.LOG_BITS;c++)this.member(c)&&(0<c&&d&&(b+=","),b=a?b+a.getTokenDisplayName(c):b+c.toString(),d=!0);return b+"}"},toString2:function(a,b){var c="",d;for(d=0;d<this.bits.length<<org.antlr.runtime.BitSet.LOG_BITS;d++)this.member(d)&&
(0<c.length&&(c+=a),c=d>=b.size()?c+("'"+d+"'"):org.antlr.lang.isValue(b.get(d))?c+b.get(d):c+("'"+d+"'"));return c}};org.antlr.runtime.CharStream=function(){};org.antlr.runtime.IntStream=function(){};org.antlr.lang.extend(org.antlr.runtime.CharStream,org.antlr.runtime.IntStream);org.antlr.lang.augmentObject(org.antlr.runtime.CharStream,{EOF:-1});org.antlr.runtime.Token=function(){};
org.antlr.lang.augmentObject(org.antlr.runtime.Token,{EOR_TOKEN_TYPE:1,DOWN:2,UP:3,MIN_TOKEN_TYPE:4,EOF:org.antlr.runtime.CharStream.EOF,EOF_TOKEN:null,INVALID_TOKEN_TYPE:0,INVALID_TOKEN:null,SKIP_TOKEN:null,DEFAULT_CHANNEL:0,HIDDEN_CHANNEL:99});
org.antlr.runtime.CommonToken=function(){var a;this.charPositionInLine=-1;this.channel=0;this.index=-1;1==arguments.length?org.antlr.lang.isNumber(arguments[0])?this.type=arguments[0]:(a=arguments[0],this.text=a.getText(),this.type=a.getType(),this.line=a.getLine(),this.index=a.getTokenIndex(),this.charPositionInLine=a.getCharPositionInLine(),this.channel=a.getChannel(),a instanceof org.antlr.runtime.CommonToken&&(this.start=a.start,this.stop=a.stop)):2==arguments.length?(this.type=arguments[0],this.text=
arguments[1],this.channel=0):5==arguments.length&&(this.input=arguments[0],this.type=arguments[1],this.channel=arguments[2],this.start=arguments[3],this.stop=arguments[4])};
org.antlr.lang.extend(org.antlr.runtime.CommonToken,org.antlr.runtime.Token,{getType:function(){return this.type},setLine:function(a){this.line=a},getText:function(){return org.antlr.lang.isString(this.text)?this.text:!this.input?null:this.text=this.input.substring(this.start,this.stop)},setText:function(a){this.text=a},getLine:function(){return this.line},getCharPositionInLine:function(){return this.charPositionInLine},setCharPositionInLine:function(a){this.charPositionInLine=a},getChannel:function(){return this.channel},
setChannel:function(a){this.channel=a},setType:function(a){this.type=a},getStartIndex:function(){return this.start},setStartIndex:function(a){this.start=a},getStopIndex:function(){return this.stop},setStopIndex:function(a){this.stop=a},getTokenIndex:function(){return this.index},setTokenIndex:function(a){this.index=a},getInputStream:function(){return this.input},setInputStream:function(a){this.input=a},toString:function(){var a="";0<this.channel&&(a=",channel="+this.channel);var b=this.getText();
org.antlr.lang.isNull(b)?b="<no text>":(b=b.replace(/\n/g,"\\\\n"),b=b.replace(/\r/g,"\\\\r"),b=b.replace(/\t/g,"\\\\t"));return"[@"+this.getTokenIndex()+","+this.start+":"+this.stop+"='"+b+"',<"+this.type+">"+a+","+this.line+":"+this.getCharPositionInLine()+"]"}});org.antlr.lang.augmentObject(org.antlr.runtime.Token,{EOF_TOKEN:new org.antlr.runtime.CommonToken(org.antlr.runtime.CharStream.EOF),INVALID_TOKEN:new org.antlr.runtime.CommonToken(0),SKIP_TOKEN:new org.antlr.runtime.CommonToken(0)},!0);
org.antlr.runtime.tree.RewriteCardinalityException=function(a){this.elementDescription=a};org.antlr.lang.extend(org.antlr.runtime.tree.RewriteCardinalityException,Error,{getMessage:function(){return org.antlr.lang.isString(this.elementDescription)?this.elementDescription:null},name:function(){return"org.antlr.runtime.tree.RewriteCardinalityException"}});
org.antlr.runtime.tree.RewriteEmptyStreamException=function(a){org.antlr.runtime.tree.RewriteEmptyStreamException.superclass.constructor.call(this,a)};org.antlr.lang.extend(org.antlr.runtime.tree.RewriteEmptyStreamException,org.antlr.runtime.tree.RewriteCardinalityException,{name:function(){return"org.antlr.runtime.tree.RewriteEmptyStreamException"}});
org.antlr.runtime.tree.RewriteEarlyExitException=function(a){var b=org.antlr.runtime.tree.RewriteEarlyExitException.superclass;org.antlr.lang.isUndefined(a)&&(a=null);b.constructor.call(this,a)};org.antlr.lang.extend(org.antlr.runtime.tree.RewriteEarlyExitException,org.antlr.runtime.tree.RewriteCardinalityException,{name:function(){return"org.antlr.runtime.tree.RewriteEarlyExitException"}});
org.antlr.runtime.MismatchedTreeNodeException=function(a,b){a&&b&&(org.antlr.runtime.MismatchedTreeNodeException.superclass.constructor.call(this,b),this.expecting=a)};org.antlr.lang.extend(org.antlr.runtime.MismatchedTreeNodeException,org.antlr.runtime.RecognitionException,{toString:function(){return"MismatchedTreeNodeException("+this.getUnexpectedType()+"!="+this.expecting+")"},name:"org.antlr.runtime.MismatchedTreeNodeException"});org.antlr.runtime.tree.Tree=function(){};
org.antlr.runtime.tree.BaseTree=function(){};
org.antlr.lang.extend(org.antlr.runtime.tree.BaseTree,org.antlr.runtime.tree.Tree,{getChild:function(a){return!this.children||a>=this.children.length?null:this.children[a]},getChildren:function(){return this.children},getFirstChildWithType:function(a){var b,c;for(b=0;this.children&&b<this.children.length;b++)if(c=this.children[b],c.getType()===a)return c;return null},getChildCount:function(){return!this.children?0:this.children.length},addChild:function(a){if(org.antlr.lang.isValue(a)){var b,c,d;
if(a.isNil()){if(this.children&&this.children==a.children)throw Error("attempt to add child list to itself");if(a.children)if(this.children){b=a.children.length;for(c=0;c<b;c++)d=a.children[c],this.children.push(d),d.setParent(this),d.setChildIndex(this.children.length-1)}else this.children=a.children,this.freshenParentAndChildIndexes()}else this.children||(this.children=this.createChildrenList()),this.children.push(a),a.setParent(this),a.setChildIndex(this.children.length-1)}},addChildren:function(a){var b,
c;for(b=0;b<a.length;b++)c=a[b],this.addChild(c)},setChild:function(a,b){if(b){if(b.isNil())throw Error("Can't set single child to a list");this.children||(this.children=this.createChildrenList());this.children[a]=b;b.setParent(this);b.setChildIndex(a)}},deleteChild:function(a){if(!this.children)return null;if(0>a||a>=this.children.length)throw Error("Index out of bounds.");var b=this.children.splice(a,1)[0];this.freshenParentAndChildIndexes(a);return b},replaceChildren:function(a,b,c){if(!this.children)throw Error("indexes invalid; no children in list");
var d=b-a+1,e,f=null;c.isNil()?f=c.children:(f=[],f.push(c));var g=e=f.length,c=d-e;if(0===c)for(c=0;a<=b;a++)d=f[c],this.children[a]=d,d.setParent(this),d.setChildIndex(a),c++;else{if(0<c){for(c=0;c<g;c++)this.children[a+c]=f[c];for(d=f=a+g;d<=b;d++)this.children.splice(f,1)}else{for(c=0;c<d;c++)this.children[a+c]=f[c];for(c=d;c<e;c++)this.children.splice(a+c,0,f[c])}this.freshenParentAndChildIndexes(a)}},createChildrenList:function(){return[]},isNil:function(){return!1},freshenParentAndChildIndexes:function(a){org.antlr.lang.isNumber(a)||
(a=0);for(var b=this.getChildCount(),c;a<b;a++)c=this.getChild(a),c.setChildIndex(a),c.setParent(this)},sanityCheckParentAndChildIndexes:function(a,b){0===arguments.length&&(a=null,b=-1);if(a!==this.getParent())throw Error("parents don't match; expected "+a+" found "+this.getParent());if(b!==this.getChildIndex())throw Error("child indexes don't match; expected "+b+" found "+this.getChildIndex());var c=this.getChildCount(),d,e;for(d=0;d<c;d++)e=this.getChild(d),e.sanityCheckParentAndChildIndexes(this,
d)},getChildIndex:function(){return 0},setChildIndex:function(){},getParent:function(){return null},setParent:function(){},getTree:function(){return this},toStringTree:function(){if(!this.children||0===this.children.length)return this.toString();var a="",b,c;this.isNil()||(a=a+"("+this.toString(),a+=" ");for(b=0;this.children&&b<this.children.length;b++)c=this.children[b],0<b&&(a+=" "),a+=c.toStringTree();this.isNil()||(a+=")");return a},getLine:function(){return 0},getCharPositionInLine:function(){return 0}});
org.antlr.runtime.tree.CommonTree=function(a){this.childIndex=this.stopIndex=this.startIndex=-1;this.token=this.parent=null;a instanceof org.antlr.runtime.tree.CommonTree?(org.antlr.runtime.tree.CommonTree.superclass.constructor.call(this,a),this.token=a.token,this.startIndex=a.startIndex,this.stopIndex=a.stopIndex):a instanceof org.antlr.runtime.CommonToken&&(this.token=a)};
org.antlr.lang.extend(org.antlr.runtime.tree.CommonTree,org.antlr.runtime.tree.BaseTree,{getToken:function(){return this.token},dupNode:function(){return new org.antlr.runtime.tree.CommonTree(this)},isNil:function(){return!this.token},getType:function(){return!this.token?org.antlr.runtime.Token.INVALID_TOKEN_TYPE:this.token.getType()},getText:function(){return!this.token?null:this.token.getText()},getLine:function(){return!this.token||0===this.token.getLine()?0<this.getChildCount()?this.getChild(0).getLine():
0:this.token.getLine()},getCharPositionInLine:function(){return!this.token||-1===this.token.getCharPositionInLine()?0<this.getChildCount()?this.getChild(0).getCharPositionInLine():0:this.token.getCharPositionInLine()},getTokenStartIndex:function(){return this.token?this.token.getTokenIndex():this.startIndex},setTokenStartIndex:function(a){this.startIndex=a},getTokenStopIndex:function(){return this.token?this.token.getTokenIndex():this.stopIndex},setTokenStopIndex:function(a){this.stopIndex=a},getChildIndex:function(){return this.childIndex},
getParent:function(){return this.parent},setParent:function(a){this.parent=a},setChildIndex:function(a){this.childIndex=a},toString:function(){return this.isNil()?"nil":this.getType()===org.antlr.runtime.Token.INVALID_TOKEN_TYPE?"<errornode>":!this.token?null:this.token.getText()}});org.antlr.runtime.tree.Tree.INVALID_NODE=new org.antlr.runtime.tree.CommonTree(org.antlr.runtime.Token.INVALID_TOKEN);
org.antlr.runtime.tree.CommonErrorNode=function(a,b,c,d){if(!c||c.getTokenIndex()<b.getTokenIndex()&&c.getType()!=org.antlr.runtime.Token.EOF)c=b;this.input=a;this.start=b;this.stop=c;this.trappedException=d};
org.antlr.lang.extend(org.antlr.runtime.tree.CommonErrorNode,org.antlr.runtime.tree.CommonTree,{isNil:function(){return!1},getType:function(){return org.antlr.runtime.Token.INVALID_TOKEN_TYPE},getText:function(){var a=null;if(this.start instanceof org.antlr.runtime.Token){var a=this.start.getTokenIndex(),b=this.stop.getTokenIndex();this.stop.getType()===org.antlr.runtime.Token.EOF&&(b=this.input.size());a=this.input.toString(a,b)}else a=this.start instanceof org.antlr.runtime.tree.Tree?this.input.toString(this.start,
this.stop):"<unknown>";return a},toString:function(){return this.trappedException instanceof org.antlr.runtime.MissingTokenException?"<missing type: "+this.trappedException.getMissingType()+">":this.trappedException instanceof org.antlr.runtime.UnwantedTokenException?"<extraneous: "+this.trappedException.getUnexpectedToken()+", resync="+this.getText()+">":this.trappedException instanceof org.antlr.runtime.MismatchedTokenException?"<mismatched token: "+this.trappedException.token+", resync="+this.getText()+
">":this.trappedException instanceof org.antlr.runtime.NoViableAltException?"<unexpected: "+this.trappedException.token+", resync="+this.getText()+">":"<error: "+this.getText()+">"}});org.antlr.runtime.tree.BaseTreeAdaptor=function(){this.uniqueNodeID=1};org.antlr.runtime.tree.TreeAdaptor=function(){};
org.antlr.lang.extend(org.antlr.runtime.tree.BaseTreeAdaptor,org.antlr.runtime.tree.TreeAdaptor,{nil:function(){return this.create(null)},errorNode:function(a,b,c,d){return new org.antlr.runtime.tree.CommonErrorNode(a,b,c,d)},isNil:function(a){return a.isNil()},dupTree:function(a,b){1===arguments.length&&(b=null);if(!a)return null;var c=this.dupNode(a);this.setChildIndex(c,this.getChildIndex(a));this.setParent(c,b);var d=this.getChildCount(a),e,f;for(e=0;e<d;e++)f=this.getChild(a,e),f=this.dupTree(f,
a),this.addChild(c,f);return c},addChild:function(a,b){a&&org.antlr.lang.isValue(b)&&a.addChild(b)},becomeRoot:function(a,b){if(a instanceof org.antlr.runtime.Token||!a)a=this.create(a);var c=a;if(!b)return a;if(c.isNil()){var d=c.getChildCount();if(1===d)c=c.getChild(0);else if(1<d)throw Error("more than one node as root (TODO: make exception hierarchy)");}c.addChild(b);return c},rulePostProcessing:function(a){a&&a.isNil()&&(0===a.getChildCount()?a=null:1===a.getChildCount()&&(a=a.getChild(0),a.setParent(null),
a.setChildIndex(-1)));return a},create:function(a,b){var c;if(2===arguments.length)return org.antlr.lang.isString(arguments[1])?(c=arguments[1],b=this.createToken(a,c)):(b=this.createToken(b),b.setType(a)),c=this.create(b);if(3===arguments.length)return c=arguments[2],b=this.createToken(b),b.setType(a),b.setText(c),c=this.create(b)},getType:function(a){a.getType();return 0},setType:function(){throw Error("don't know enough about Tree node");},getText:function(a){return a.getText()},setText:function(){throw Error("don't know enough about Tree node");
},getChild:function(a,b){return a.getChild(b)},setChild:function(a,b,c){a.setChild(b,c)},deleteChild:function(a,b){return a.deleteChild(b)},getChildCount:function(a){return a.getChildCount()},getUniqueID:function(a){this.treeToUniqueIDMap||(this.treeToUniqueIDMap={});var b=this.treeToUniqueIDMap[a];if(org.antlr.lang.isValue(b))return b;b=this.uniqueNodeID;this.treeToUniqueIDMap[a]=b;this.uniqueNodeID++;return b}});org.antlr.runtime.tree.CommonTreeAdaptor=function(){};
org.antlr.lang.extend(org.antlr.runtime.tree.CommonTreeAdaptor,org.antlr.runtime.tree.BaseTreeAdaptor,{dupNode:function(a){return!org.antlr.lang.isValue(a)?null:a.dupNode()},create:function(a){return 1<arguments.length?org.antlr.runtime.tree.CommonTreeAdaptor.superclass.create.apply(this,arguments):new org.antlr.runtime.tree.CommonTree(a)},createToken:function(a){return 2===arguments.length?new org.antlr.runtime.CommonToken(arguments[0],arguments[1]):new org.antlr.runtime.CommonToken(arguments[0])},
setTokenBoundaries:function(a,b,c){if(org.antlr.lang.isValue(a)){var d=0,e=0;org.antlr.lang.isValue(b)&&(d=b.getTokenIndex?b.getTokenIndex():b.getStartIndex?b.getStartIndex():b.getTokenStartIndex());org.antlr.lang.isValue(c)&&(e=e.getTokenIndex?c.getTokenIndex():c.getStopIndex?c.getStopIndex():c.getTokenStopIndex());a.setTokenStartIndex(d);a.setTokenStopIndex(e)}},getTokenStartIndex:function(a){return!a?-1:a.getTokenStartIndex()},getTokenStopIndex:function(a){return!a?-1:a.getTokenStopIndex()},getText:function(a){return!a?
null:a.getText()},getType:function(a){return!a?org.antlr.runtime.Token.INVALID_TOKEN_TYPE:a.getType()},getToken:function(a){return a instanceof org.antlr.runtime.tree.CommonTree?a.getToken():null},getChild:function(a,b){return!a?null:a.getChild(b)},getChildCount:function(a){return!a?0:a.getChildCount()},getParent:function(a){return a.getParent()},setParent:function(a,b){a.setParent(b)},getChildIndex:function(a){return a.getChildIndex()},setChildIndex:function(a,b){a.setChildIndex(b)},replaceChildren:function(a,
b,c,d){a&&a.replaceChildren(b,c,d)}});org.antlr.runtime.ANTLRStringStream=function(a){this.p=0;this.line=1;this.markDepth=this.charPositionInLine=0;this.lastMarker=this.markers=null;this.data=a;this.n=a.length};
org.antlr.lang.extend(org.antlr.runtime.ANTLRStringStream,org.antlr.runtime.CharStream,{reset:function(){this.p=0;this.line=1;this.markDepth=this.charPositionInLine=0},consume:function(){this.p<this.n&&(this.charPositionInLine++,"\n"===this.data.charAt(this.p)&&(this.line++,this.charPositionInLine=0),this.p++)},LA:function(a){0>a&&a++;a=this.p+a-1;return a>=this.n||0>a?org.antlr.runtime.CharStream.EOF:this.data.charAt(a)},index:function(){return this.p},size:function(){return this.n},mark:function(){this.markers||
(this.markers=[],this.markers.push(null));this.markDepth++;var a=null;this.markDepth>=this.markers.length?(a={},this.markers.push(a)):a=this.markers[this.markDepth];a.p=this.p;a.line=this.line;a.charPositionInLine=this.charPositionInLine;return this.lastMarker=this.markDepth},rewind:function(a){org.antlr.lang.isNumber(a)||(a=this.lastMarker);var b=this.markers[a];this.seek(b.p);this.line=b.line;this.charPositionInLine=b.charPositionInLine;this.release(a)},release:function(a){this.markDepth=a;this.markDepth--},
seek:function(a){if(a<=this.p)this.p=a;else for(;this.p<a;)this.consume()},substring:function(a,b){return this.data.substr(a,b-a+1)},getLine:function(){return this.line},getCharPositionInLine:function(){return this.charPositionInLine},setLine:function(a){this.line=a},setCharPositionInLine:function(a){this.charPositionInLine=a},getSourceName:function(){return null}});org.antlr.runtime.ANTLRStringStream.prototype.LT=org.antlr.runtime.ANTLRStringStream.prototype.LA;
org.antlr.runtime.CommonTokenStream=function(a,b){this.p=-1;this.channel=org.antlr.runtime.Token.DEFAULT_CHANNEL;this.v_discardOffChannelTokens=!1;this.tokens=[];2<=arguments.length?this.channel=b:1===arguments.length&&(this.tokenSource=a)};org.antlr.runtime.TokenStream=function(){};
org.antlr.lang.extend(org.antlr.runtime.CommonTokenStream,org.antlr.runtime.TokenStream,{setTokenSource:function(a){this.tokenSource=a;this.tokens=[];this.p=-1;this.channel=org.antlr.runtime.Token.DEFAULT_CHANNEL},fillBuffer:function(){for(var a=0,b=this.tokenSource.nextToken(),c,d;org.antlr.lang.isValue(b)&&b.getType()!=org.antlr.runtime.CharStream.EOF;)c=!1,this.channelOverrideMap&&(d=this.channelOverrideMap[b.getType()],org.antlr.lang.isValue(d)&&b.setChannel(d)),this.discardSet&&this.discardSet[b.getType()]?
c=!0:this.v_discardOffChannelTokens&&b.getChannel()!=this.channel&&(c=!0),c||(b.setTokenIndex(a),this.tokens.push(b),a++),b=this.tokenSource.nextToken();this.p=0;this.p=this.skipOffTokenChannels(this.p)},consume:function(){this.p<this.tokens.length&&(this.p++,this.p=this.skipOffTokenChannels(this.p))},skipOffTokenChannels:function(a){for(var b=this.tokens.length;a<b&&this.tokens[a].getChannel()!=this.channel;)a++;return a},skipOffTokenChannelsReverse:function(a){for(;0<=a&&this.tokens[a].getChannel()!=
this.channel;)a--;return a},setTokenTypeChannel:function(a,b){this.channelOverrideMap||(this.channelOverrideMap={});this.channelOverrideMap[a]=b},discardTokenType:function(a){this.discardSet||(this.discardSet={});this.discardSet[a]=!0},discardOffChannelTokens:function(a){this.v_discardOffChannelTokens=a},getTokens:function(a,b,c){-1===this.p&&this.fillBuffer();if(0===arguments.length)return this.tokens;org.antlr.lang.isArray(c)?c=new org.antlr.runtime.BitSet(c):org.antlr.lang.isNumber(c)&&(c=org.antlr.runtime.BitSet.of(c));
b>=this.tokens.length&&(b=this.tokens.length-1);0>a&&(a=0);if(a>b)return null;var d=[],e,f;for(e=a;e<=b;e++)f=this.tokens[e],(!this.types||c.member(f.getType()))&&d.push(f);0===d.length&&(d=null);return d},LT:function(a){-1===this.p&&this.fillBuffer();if(0===a)return null;if(0>a)return this.LB(-1*a);if(this.p+a-1>=this.tokens.length)return org.antlr.runtime.Token.EOF_TOKEN;for(var b=this.p,c=1;c<a;)b=this.skipOffTokenChannels(b+1),c++;return b>=this.tokens.length?org.antlr.runtime.Token.EOF_TOKEN:
this.tokens[b]},LB:function(a){-1===this.p&&this.fillBuffer();if(0===a||0>this.p-a)return null;for(var b=this.p,c=1;c<=a;)b=this.skipOffTokenChannelsReverse(b-1),c++;return 0>b?null:this.tokens[b]},get:function(a){return this.tokens[a]},LA:function(a){return this.LT(a).getType()},mark:function(){-1===this.p&&this.fillBuffer();return this.lastMarker=this.index()},release:function(){},size:function(){return this.tokens.length},index:function(){return this.p},rewind:function(a){org.antlr.lang.isNumber(a)||
(a=this.lastMarker);this.seek(a)},reset:function(){this.lastMarker=this.p=0},seek:function(a){this.p=a},getTokenSource:function(){return this.tokenSource},getSourceName:function(){return this.getTokenSource().getSourceName()},toString:function(a,b){0===arguments.length&&(-1===this.p&&this.fillBuffer(),a=0,b=this.tokens.length-1);if(!org.antlr.lang.isNumber(a)&&!org.antlr.lang.isNumber(b))if(org.antlr.lang.isValue(a)&&org.antlr.lang.isValue(b))a=a.getTokenIndex(),b=b.getTokenIndex();else return null;
var c="",d;if(0>a||0>b)return null;-1==this.p&&this.fillBuffer();b>=this.tokens.length&&(b=this.tokens.length-1);for(d=a;d<=b;d++)c+=this.tokens[d].getText();return c}});org.antlr.runtime.TokenRewriteStream=function(){var a=org.antlr.runtime.TokenRewriteStream.superclass;this.lastRewriteTokenIndexes=this.programs=null;0!==arguments.length&&a.constructor.apply(this,arguments);this.init()};
(function(){var a=org.antlr.runtime.TokenRewriteStream;org.antlr.lang.augmentObject(a,{DEFAULT_PROGRAM_NAME:"default",PROGRAM_INIT_SIZE:100,MIN_TOKEN_INDEX:0});a.RewriteOperation=function(a,c){this.index=a;this.text=c};a.RewriteOperation.prototype={execute:function(){return this.index},toString:function(){return this.text}};a.InsertBeforeOp=function(b,c){a.InsertBeforeOp.superclass.constructor.call(this,b,c)};org.antlr.lang.extend(a.InsertBeforeOp,a.RewriteOperation,{execute:function(a){a.push(this.text);
return this.index}});a.ReplaceOp=function(b,c,d){a.ReplaceOp.superclass.constructor.call(this,b,d);this.lastIndex=c};org.antlr.lang.extend(a.ReplaceOp,a.RewriteOperation,{execute:function(a){org.antlr.lang.isValue(this.text)&&a.push(this.text);return this.lastIndex+1}});a.DeleteOp=function(b,c){a.DeleteOp.superclass.constructor.call(this,b,c)};org.antlr.lang.extend(a.DeleteOp,a.ReplaceOp);org.antlr.lang.extend(a,org.antlr.runtime.CommonTokenStream,{init:function(){this.programs={};this.programs[a.DEFAULT_PROGRAM_NAME]=
[];this.lastRewriteTokenIndexes={}},rollback:function(){var b;1===arguments.length?b=a.DEFAULT_PROGRAM_NAME:2===arguments.length&&(b=arguments[0]);var c=this.programs[b];c&&(programs[b]=c.slice(a.MIN_TOKEN_INDEX,this.instructionIndex))},deleteProgram:function(b){b=b||a.DEFAULT_PROGRAM_NAME;this.rollback(b,a.MIN_TOKEN_INDEX)},addToSortedRewriteList:function(){var b,c;1===arguments.length?(b=a.DEFAULT_PROGRAM_NAME,c=arguments[0]):2===arguments.length&&(b=arguments[0],c=arguments[1]);b=this.getProgram(b);
var d,e,f,g,h;e=0;for(d=b.length;e<d;e++)if(f=b[e],f.index===c.index){if(c instanceof a.ReplaceOp){f=!1;for(h=e;h<b.length;h++){g=b[e];if(g.index!==c.index)break;if(g instanceof a.ReplaceOp){b[e]=c;f=!0;break}}f||b.splice(h,0,c)}else b.splice(e,0,c);break}else if(f.index>c.index){b.splice(e,0,c);break}e===d&&b.push(c)},insertAfter:function(){var b,c,d;2===arguments.length?(c=a.DEFAULT_PROGRAM_NAME,b=arguments[0],d=arguments[1]):3===arguments.length&&(c=arguments[0],b=arguments[1],d=arguments[2]);
b instanceof org.antlr.runtime.Token&&(b=b.index);this.insertBefore(c,b+1,d)},insertBefore:function(){var b,c,d;2===arguments.length?(c=a.DEFAULT_PROGRAM_NAME,b=arguments[0],d=arguments[1]):3===arguments.length&&(c=arguments[0],b=arguments[1],d=arguments[2]);b instanceof org.antlr.runtime.Token&&(b=b.index);this.addToSortedRewriteList(c,new a.InsertBeforeOp(b,d))},replace:function(){var b,c,d,e;2===arguments.length?(b=a.DEFAULT_PROGRAM_NAME,c=arguments[0],d=arguments[0],e=arguments[1]):3===arguments.length&&
(b=a.DEFAULT_PROGRAM_NAME,c=arguments[0],d=arguments[1],e=arguments[2]);4===arguments.length&&(b=arguments[0],c=arguments[1],d=arguments[2],e=arguments[3]);c instanceof org.antlr.runtime.Token&&(c=c.index);d instanceof org.antlr.runtime.Token&&(d=d.index);c>d||(0>d||0>c)||this.addToSortedRewriteList(b,new a.ReplaceOp(c,d,e))},remove:function(){for(var a=[],c=arguments.length-1;0<=c;)a[c]=arguments[c],c--;a.push("");this.replace.apply(this,a)},getLastRewriteTokenIndex:function(b){b=b||a.DEFAULT_PROGRAM_NAME;
return this.lastRewriteTokenIndexes[b]||-1},setLastRewriteTokenIndex:function(a,c){this.lastRewriteTokenIndexes[a]=c},getProgram:function(a){var c=this.programs[a];c||(c=this.initializeProgram(a));return c},initializeProgram:function(a){var c=[];return this.programs[a]=c},toOriginalString:function(b,c){org.antlr.lang.isNumber(b)||(b=a.MIN_TOKEN_INDEX);org.antlr.lang.isNumber(c)||(c=this.size()-1);var d=[],e;for(e=b;e>=a.MIN_TOKEN_INDEX&&e<=c&&e<this.tokens.length;e++)d.push(this.get(e).getText());
return d.join("")},toString:function(){var b,c,d;0===arguments.length?(b=a.DEFAULT_PROGRAM_NAME,c=a.MIN_TOKEN_INDEX,d=this.size()-1):1===arguments.length?(b=arguments[0],c=a.MIN_TOKEN_INDEX,d=this.size()-1):2===arguments.length&&(b=a.DEFAULT_PROGRAM_NAME,c=arguments[0],d=arguments[1]);b=this.programs[b];if(!b||0===b.length)return this.toOriginalString(c,d);var e=0,f=c;c=[];for(var g;f>=a.MIN_TOKEN_INDEX&&f<=d&&f<this.tokens.length;){if(e<b.length){for(g=b[e];g.index<f&&e<b.length;)e++,e<b.length&&
(g=b[e]);for(;f===g.index&&e<b.length;)f=g.execute(c),e++,e<b.length&&(g=b[e])}f<=d&&(c.push(this.get(f).getText()),f++)}for(d=e;d<b.length;d++)g=b[d],g.index>=this.size()&&g.execute(c);return c.join("")},toDebugString:function(b,c){org.antlr.lang.isNumber(b)||(b=a.MIN_TOKEN_INDEX);org.antlr.lang.isNumber(c)||(c=this.size()-1);var d=[],e;for(e=b;e>=a.MIN_TOKEN_INDEX&&e<=c&&e<this.tokens.length;e++)d.push(this.get(e));return d.join("")}})})();org.antlr.runtime.tree.TreeNodeStream=function(){};
org.antlr.lang.extend(org.antlr.runtime.tree.TreeNodeStream,org.antlr.runtime.IntStream);
org.antlr.runtime.tree.CommonTreeNodeStream=function(a,b,c){1===arguments.length&&(b=a,a=new org.antlr.runtime.tree.CommonTreeAdaptor);2>=arguments.length&&(c=org.antlr.runtime.tree.CommonTreeNodeStream.DEFAULT_INITIAL_BUFFER_SIZE);this.uniqueNavigationNodes=!1;this.p=-1;var d=org.antlr.runtime.Token;this.root=b;this.adaptor=a;this.nodes=[];this.down=this.adaptor.create(d.DOWN,"DOWN");this.up=this.adaptor.create(d.UP,"UP");this.eof=this.adaptor.create(d.EOF,"EOF")};
org.antlr.lang.augmentObject(org.antlr.runtime.tree.CommonTreeNodeStream,{DEFAULT_INITIAL_BUFFER_SIZE:100,INITIAL_CALL_STACK_SIZE:10});
org.antlr.lang.extend(org.antlr.runtime.tree.CommonTreeNodeStream,org.antlr.runtime.tree.TreeNodeStream,{StreamIterator:function(){var a=0,b=this.nodes,c=this.eof;return{hasNext:function(){return a<b.length},next:function(){var d=a;a++;return d<b.length?b[d]:c},remove:function(){throw Error("cannot remove nodes from stream");}}},fillBuffer:function(a){var b=!1;org.antlr.lang.isUndefined(a)&&(a=this.root,b=!0);var c=this.adaptor.isNil(a);c||this.nodes.push(a);var d=this.adaptor.getChildCount(a);!c&&
0<d&&this.addNavigationNode(org.antlr.runtime.Token.DOWN);var e,f;for(e=0;e<d;e++)f=this.adaptor.getChild(a,e),this.fillBuffer(f);!c&&0<d&&this.addNavigationNode(org.antlr.runtime.Token.UP);b&&(this.p=0)},getNodeIndex:function(a){-1==this.p&&this.fillBuffer();var b,c;for(b=0;b<this.nodes.length;b++)if(c=this.nodes[b],c===a)return b;return-1},addNavigationNode:function(a){var b=null,b=a===org.antlr.runtime.Token.DOWN?this.hasUniqueNavigationNodes()?this.adaptor.create(org.antlr.runtime.Token.DOWN,
"DOWN"):this.down:this.hasUniqueNavigationNodes()?this.adaptor.create(org.antlr.runtime.Token.UP,"UP"):this.up;this.nodes.push(b)},get:function(a){-1===this.p&&this.fillBuffer();return this.nodes[a]},LT:function(a){-1===this.p&&this.fillBuffer();return 0===a?null:0>a?this.LB(-1*a):this.p+a-1>=this.nodes.length?this.eof:this.nodes[this.p+a-1]},getCurrentSymbol:function(){return this.LT(1)},LB:function(a){return 0===a||0>this.p-a?null:this.nodes[this.p-a]},getTreeSource:function(){return this.root},
getSourceName:function(){return this.getTokenStream().getSourceName()},getTokenStream:function(){return this.tokens},setTokenStream:function(a){this.tokens=a},getTreeAdaptor:function(){return this.adaptor},setTreeAdaptor:function(a){this.adaptor=a},hasUniqueNavigationNodes:function(){return this.uniqueNavigationNodes},setUniqueNavigationNodes:function(a){this.uniqueNavigationNodes=a},consume:function(){-1===this.p&&this.fillBuffer();this.p++},LA:function(a){return this.adaptor.getType(this.LT(a))},
mark:function(){-1===this.p&&this.fillBuffer();return this.lastMarker=this.index()},release:function(){},index:function(){return this.p},rewind:function(a){org.antlr.lang.isNumber(a)||(a=this.lastMarker);this.seek(a)},seek:function(a){-1===this.p&&this.fillBuffer();this.p=a},push:function(a){this.calls||(this.calls=[]);this.calls.push(this.p);this.seek(a)},pop:function(){var a=this.calls.pop();this.seek(a);return a},reset:function(){this.lastMarker=this.p=0;this.calls&&(this.calls=[])},size:function(){-1===
this.p&&this.fillBuffer();return this.nodes.length},iterator:function(){-1===this.p&&this.fillBuffer();return this.StreamIterator()},replaceChildren:function(a,b,c,d){a&&this.adaptor.replaceChildren(a,b,c,d)},toTokenString:function(a,b){-1===this.p&&this.fillBuffer();var c="",d,e;for(d=a;d<this.nodes.length&&d<=b;d++)e=this.nodes[d],c+=" "+this.adaptor.getToken(e);return c},toString:function(a,b){var c="",d,e,f;if(0===arguments.length){-1===this.p&&this.fillBuffer();for(f=0;f<this.nodes.length;f++)e=
this.nodes[f],c+=" ",c+=this.adaptor.getType(e)}else{if(!org.antlr.lang.isNumber(a)||!org.antlr.lang.isNumber(b))return null;-1===this.p&&this.fillBuffer();if(this.tokens)return c=this.adaptor.getTokenStartIndex(a),d=this.adaptor.getTokenStopIndex(b),this.adaptor.getType(b)===org.antlr.runtime.Token.UP?d=this.adaptor.getTokenStopIndex(a):this.adaptor.getType(b)==org.antlr.runtime.Token.EOF&&(d=this.size()-2),this.tokens.toString(c,d);for(f=0;f<this.nodes.length&&!(e=this.nodes[f],e===a);f++);c="";
for(e=this.nodes[f];e!==b;)d=this.adaptor.getText(e),org.antlr.lang.isString(d)||(d=" "+this.adaptor.getType(e).toString()),c+=d,f++,e=nodes[f];d=this.adaptor.getText(b);org.antlr.lang.isString(d)||(d=" "+this.adaptor.getType(b).toString());c+=d}return c}});org.antlr.runtime.tree.RewriteRuleElementStream=function(a,b,c){this.cursor=0;this.dirty=!1;this.elementDescription=b;this.adaptor=a;c&&(org.antlr.lang.isArray(c)?(this.singleElement=null,this.elements=c):this.add(c))};
org.antlr.runtime.tree.RewriteRuleElementStream.prototype={reset:function(){this.cursor=0;this.dirty=!0},add:function(a){org.antlr.lang.isValue(a)&&(this.elements?this.elements.push(a):org.antlr.lang.isValue(this.singleElement)?(this.elements=[],this.elements.push(this.singleElement),this.singleElement=null,this.elements.push(a)):this.singleElement=a)},nextTree:function(){var a=this.size();return this.dirty||this.cursor>=a&&1==a?(a=this._next(),this.dup(a)):a=this._next()},_next:function(){var a=
this.size();if(0===a)throw new org.antlr.runtime.tree.RewriteEmptyStreamException(this.elementDescription);if(this.cursor>=a){if(1===a)return this.toTree(this.singleElement);throw new org.antlr.runtime.tree.RewriteCardinalityException(this.elementDescription);}if(org.antlr.lang.isValue(this.singleElement))return this.cursor++,this.toTree(this.singleElement);a=this.toTree(this.elements[this.cursor]);this.cursor++;return a},toTree:function(a){return a&&a.getTree?a.getTree():a},hasNext:function(){return org.antlr.lang.isValue(this.singleElement)&&
1>this.cursor||this.elements&&this.cursor<this.elements.length},size:function(){var a=0;org.antlr.lang.isValue(this.singleElement)&&(a=1);return this.elements?this.elements.length:a},getDescription:function(){return this.elementDescription}};org.antlr.runtime.tree.RewriteRuleNodeStream=function(a,b,c){org.antlr.runtime.tree.RewriteRuleNodeStream.superclass.constructor.apply(this,arguments)};
org.antlr.lang.extend(org.antlr.runtime.tree.RewriteRuleNodeStream,org.antlr.runtime.tree.RewriteRuleElementStream,{nextNode:function(){return this._next()},toTree:function(a){return this.adaptor.dupNode(a)},dup:function(){throw Error("dup can't be called for a node stream.");}});org.antlr.runtime.tree.RewriteRuleTokenStream=function(a,b,c){org.antlr.runtime.tree.RewriteRuleTokenStream.superclass.constructor.apply(this,arguments)};
org.antlr.lang.extend(org.antlr.runtime.tree.RewriteRuleTokenStream,org.antlr.runtime.tree.RewriteRuleElementStream,{nextNode:function(){var a=this._next();return this.adaptor.create(a)},nextToken:function(){return this._next()},toTree:function(a){return a},dup:function(){throw Error("dup can't be called for a token stream.");}});org.antlr.runtime.tree.RewriteRuleSubtreeStream=function(){org.antlr.runtime.tree.RewriteRuleSubtreeStream.superclass.constructor.apply(this,arguments)};
org.antlr.lang.extend(org.antlr.runtime.tree.RewriteRuleSubtreeStream,org.antlr.runtime.tree.RewriteRuleElementStream,{nextNode:function(){var a=this.size();return this.dirty||this.cursor>=a&&1===a?(a=this._next(),this.adaptor.dupNode(a)):a=this._next()},dup:function(a){return this.adaptor.dupTree(a)}});org.antlr.runtime.BaseRecognizer=function(a){this.state=a||new org.antlr.runtime.RecognizerSharedState};
org.antlr.lang.augmentObject(org.antlr.runtime.BaseRecognizer,{MEMO_RULE_FAILED:-2,MEMO_RULE_UNKNOWN:-1,INITIAL_FOLLOW_STACK_SIZE:100,MEMO_RULE_FAILED_I:-2,DEFAULT_TOKEN_CHANNEL:org.antlr.runtime.Token.DEFAULT_CHANNEL,HIDDEN:org.antlr.runtime.Token.HIDDEN_CHANNEL,NEXT_TOKEN_RULE_NAME:"nextToken"});
org.antlr.runtime.BaseRecognizer.prototype={reset:function(){var a,b;if(this.state&&(this.state._fsp=-1,this.state.errorRecovery=!1,this.state.lastErrorIndex=-1,this.state.failed=!1,this.state.syntaxErrors=0,this.state.backtracking=0,this.state.ruleMemo)){a=0;for(b=this.state.ruleMemo.length;a<b;a++)this.state.ruleMemo[a]=null}},match:function(a,b,c){var d=this.getCurrentInputSymbol(a);return a.LA(1)===b?(a.consume(),this.state.errorRecovery=!1,this.state.failed=!1,d):0<this.state.backtracking?(this.state.failed=
!0,d):d=this.recoverFromMismatchedToken(a,b,c)},matchAny:function(a){this.state.errorRecovery=!1;this.state.failed=!1;a.consume()},mismatchIsUnwantedToken:function(a,b){return a.LA(2)===b},mismatchIsMissingToken:function(a,b){if(!b)return!1;b.member(org.antlr.runtime.Token.EOR_TOKEN_TYPE)&&(this.computeContextSensitiveRuleFOLLOW(),b=b.or(this.viableTokensFollowingThisRule),0<=this.state._fsp&&b.remove(org.antlr.runtime.Token.EOR_TOKEN_TYPE));return b.member(a.LA(1))||b.member(org.antlr.runtime.Token.EOR_TOKEN_TYPE)?
!0:!1},mismatch:function(a,b,c){if(this.mismatchIsUnwantedToken(a,b))throw new org.antlr.runtime.UnwantedTokenException(b,a);if(this.mismatchIsMissingToken(a,c))throw new org.antlr.runtime.MissingTokenException(b,a,null);throw new org.antlr.runtime.MismatchedTokenException(b,a);},reportError:function(a){this.state.errorRecovery||(this.state.syntaxErrors++,this.state.errorRecovery=!0,this.displayRecognitionError(this.getTokenNames(),a))},displayRecognitionError:function(a,b){var c=this.getErrorHeader(b),
d=this.getErrorMessage(b,a);this.emitErrorMessage(c+" "+d)},getErrorHeader:function(a){org.antlr.lang.isNumber(a.line)||(a.line=0);return"line "+a.line+":"+a.charPositionInLine},emitErrorMessage:function(a){"undefined"!=typeof window&&window.alert?alert(a):print(a)},getErrorMessage:function(a,b){var c=a&&a.getMessage?a.getMessage():null;a instanceof org.antlr.runtime.UnwantedTokenException?(c=a.expecting==org.antlr.runtime.Token.EOF?"EOF":b[a.expecting],c="extraneous input "+this.getTokenErrorDisplay(a.getUnexpectedToken())+
" expecting "+c):a instanceof org.antlr.runtime.MissingTokenException?(c=a,c=c.expecting==org.antlr.runtime.Token.EOF?"EOF":b[c.expecting],c="missing "+c+" at "+this.getTokenErrorDisplay(a.token)):a instanceof org.antlr.runtime.MismatchedTokenException?(c=a,c=c.expecting==org.antlr.runtime.Token.EOF?"EOF":b[c.expecting],c="mismatched input "+this.getTokenErrorDisplay(a.token)+" expecting "+c):a instanceof org.antlr.runtime.NoViableAltException?c="no viable alternative at input "+this.getTokenErrorDisplay(a.token):
a instanceof org.antlr.runtime.EarlyExitException?c="required (...)+ loop did not match anything at input "+this.getTokenErrorDisplay(a.token):a instanceof org.antlr.runtime.MismatchedSetException?c="mismatched input "+this.getTokenErrorDisplay(a.token)+" expecting set "+a.expecting:a instanceof org.antlr.runtime.MismatchedNotSetException?c="mismatched input "+this.getTokenErrorDisplay(a.token)+" expecting set "+a.expecting:a instanceof org.antlr.runtime.FailedPredicateException&&(c="rule "+a.ruleName+
" failed predicate: {"+a.predicateText+"}?");return c},getNumberOfSyntaxErrors:function(){return this.state.syntaxErrors},getTokenErrorDisplay:function(a){var b=a.getText();org.antlr.lang.isValue(b)||(b=a.getType()==org.antlr.runtime.Token.EOF?"<EOF>":"<"+a.getType()+">");b=b.replace(/\n/g,"\\n");b=b.replace(/\r/g,"\\r");b=b.replace(/\t/g,"\\t");return"'"+b+"'"},recover:function(a){this.state.lastErrorIndex==a.index()&&a.consume();this.state.lastErrorIndex=a.index();var b=this.computeErrorRecoverySet();
this.beginResync();this.consumeUntil(a,b);this.endResync()},beginResync:function(){},endResync:function(){},computeErrorRecoverySet:function(){return this.combineFollows(!1)},computeContextSensitiveRuleFOLLOW:function(){return this.combineFollows(!0)},combineFollows:function(a){for(var b=this.state._fsp,c,d=new org.antlr.runtime.BitSet;0<=b;b--)if(c=this.state.following[b],d.orInPlace(c),a)if(c.member(org.antlr.runtime.Token.EOR_TOKEN_TYPE))0<b&&d.remove(org.antlr.runtime.Token.EOR_TOKEN_TYPE);else break;
return d},recoverFromMismatchedToken:function(a,b,c){var d=null;if(this.mismatchIsUnwantedToken(a,b))return d=new org.antlr.runtime.UnwantedTokenException(b,a),this.beginResync(),a.consume(),this.endResync(),this.reportError(d),b=this.getCurrentInputSymbol(a),a.consume(),b;if(this.mismatchIsMissingToken(a,c))return c=this.getMissingSymbol(a,d,b,c),d=new org.antlr.runtime.MissingTokenException(b,a,c),this.reportError(d),c;d=new org.antlr.runtime.MismatchedTokenException(b,a);throw d;},recoverFromMismatchedSet:function(a,
b,c){if(this.mismatchIsMissingToken(a,c))return this.reportError(b),this.getMissingSymbol(a,b,org.antlr.runtime.Token.INVALID_TOKEN_TYPE,c);throw b;},getCurrentInputSymbol:function(){return null},getMissingSymbol:function(){return null},consumeUntil:function(a,b){for(var c=a.LA(1);c!=org.antlr.runtime.Token.EOF&&!b.member(c);)a.consume(),c=a.LA(1)},pushFollow:function(a){if(this.state._fsp+1>=this.state.following.length){var b=[],c;for(c=this.state.following.length-1;0<=c;c--)b[c]=this.state.following[c];
this.state.following=b}this.state._fsp++;this.state.following[this.state._fsp]=a},getRuleInvocationStack:function(){throw Error("Not implemented.");},getBacktrackingLevel:function(){return this.state.backtracking},getTokenNames:function(){return null},getGrammarFileName:function(){return null},toStrings:function(a){if(!a)return null;var b=[],c;for(c=0;c<a.length;c++)b.push(a[c].getText());return b},getRuleMemoization:function(a,b){this.state.ruleMemo[a]||(this.state.ruleMemo[a]={});var c=this.state.ruleMemo[a][b];
return!org.antlr.lang.isNumber(c)?org.antlr.runtime.BaseRecognizer.MEMO_RULE_UNKNOWN:c},alreadyParsedRule:function(a,b){var c=this.getRuleMemoization(b,a.index());if(c==org.antlr.runtime.BaseRecognizer.MEMO_RULE_UNKNOWN)return!1;c==org.antlr.runtime.BaseRecognizer.MEMO_RULE_FAILED?this.state.failed=!0:a.seek(c+1);return!0},memoize:function(a,b,c){a=this.state.failed?org.antlr.runtime.BaseRecognizer.MEMO_RULE_FAILED:a.index()-1;if(!org.antlr.lang.isValue(this.state.ruleMemo))throw Error("!!!!!!!!! memo array is null for "+
this.getGrammarFileName());if(b>=this.state.ruleMemo.length)throw Error("!!!!!!!!! memo size is "+this.state.ruleMemo.length+", but rule index is "+b);org.antlr.lang.isValue(this.state.ruleMemo[b])&&(this.state.ruleMemo[b][c]=a)},getRuleMemoizationCacheSize:function(){var a=0,b;for(b=0;this.state.ruleMemo&&b<this.state.ruleMemo.length;b++){var c=this.state.ruleMemo[b];c&&(a+=c.length)}return a},traceIn:function(a,b,c){this.emitErrorMessage("enter "+a+" "+c);this.state.failed&&this.emitErrorMessage(" failed="+
this.failed);0<this.state.backtracking&&this.emitErrorMessage(" backtracking="+this.state.backtracking)},traceOut:function(a,b,c){this.emitErrorMessage("exit "+a+" "+c);this.state.failed&&this.emitErrorMessage(" failed="+this.state.failed);0<this.state.backtracking&&this.emitErrorMessage(" backtracking="+this.state.backtracking)}};org.antlr.runtime.Lexer=function(a,b){b&&org.antlr.runtime.Lexer.superclass.constructor.call(this,b);a&&(this.input=a)};
org.antlr.lang.extend(org.antlr.runtime.Lexer,org.antlr.runtime.BaseRecognizer,{reset:function(){org.antlr.runtime.Lexer.superclass.reset.call(this);org.antlr.lang.isValue(this.input)&&this.input.seek(0);org.antlr.lang.isValue(this.state)&&(this.state.token=null,this.state.type=org.antlr.runtime.Token.INVALID_TOKEN_TYPE,this.state.channel=org.antlr.runtime.Token.DEFAULT_CHANNEL,this.state.tokenStartCharIndex=-1,this.state.tokenStartCharPositionInLine=-1,this.state.tokenStartLine=-1,this.state.text=
null)},nextToken:function(){for(;;){this.state.token=null;this.state.channel=org.antlr.runtime.Token.DEFAULT_CHANNEL;this.state.tokenStartCharIndex=this.input.index();this.state.tokenStartCharPositionInLine=this.input.getCharPositionInLine();this.state.tokenStartLine=this.input.getLine();this.state.text=null;if(this.input.LA(1)===org.antlr.runtime.CharStream.EOF)return org.antlr.runtime.Token.EOF_TOKEN;try{this.mTokens();if(org.antlr.lang.isValue(this.state.token)){if(this.state.token==org.antlr.runtime.Token.SKIP_TOKEN)continue}else this.emit();
return this.state.token}catch(a){if(a instanceof org.antlr.runtime.NoViableAltException)this.reportError(a),this.recover(a);else if(a instanceof org.antlr.runtime.RecognitionException)this.reportError(a);else throw a;}}},skip:function(){this.state.token=org.antlr.runtime.Token.SKIP_TOKEN},setCharStream:function(a){this.input=null;this.reset();this.input=a},getCharStream:function(){return this.input},getSourceName:function(){return this.input.getSourceName()},emit:function(){if(0===arguments.length){var a=
new org.antlr.runtime.CommonToken(this.input,this.state.type,this.state.channel,this.state.tokenStartCharIndex,this.getCharIndex()-1);a.setLine(this.state.tokenStartLine);a.setText(this.state.text);a.setCharPositionInLine(this.state.tokenStartCharPositionInLine);return this.state.token=a}this.state.token=arguments[0]},match:function(a){var b=0;if(org.antlr.lang.isString(a))for(;b<a.length;){if(this.input.LA(1)!=a.charAt(b)){if(0<this.state.backtracking){this.state.failed=!0;break}a=new org.antlr.runtime.MismatchedTokenException(a.charAt(b),
this.input);this.recover(a);throw a;}b++;this.input.consume();this.state.failed=!1}else if(org.antlr.lang.isNumber(a)){if(this.input.LA(1)!=a){if(0<this.state.backtracking){this.state.failed=!0;return}a=new org.antlr.runtime.MismatchedTokenException(a,this.input);this.recover(a);throw a;}this.input.consume();this.state.failed=!1}},matchAny:function(){this.input.consume()},matchRange:function(a,b){if(this.input.LA(1)<a||this.input.LA(1)>b){if(0<this.state.backtracking){this.state.failed=!0;return}var c=
new org.antlr.runtime.MismatchedRangeException(a,b,this.input);this.recover(c);throw c;}this.input.consume();this.state.failed=!1},getLine:function(){return this.input.getLine()},getCharPositionInLine:function(){return this.input.getCharPositionInLine()},getCharIndex:function(){return this.input.index()},getText:function(){return org.antlr.lang.isString(this.state.text)?this.state.text:this.input.substring(this.state.tokenStartCharIndex,this.getCharIndex()-1)},setText:function(a){this.state.text=
a},reportError:function(a){this.displayRecognitionError(this.getTokenNames(),a)},getErrorMessage:function(a,b){var c=null;return c=a instanceof org.antlr.runtime.MismatchedTokenException?"mismatched character "+this.getCharErrorDisplay(a.c)+" expecting "+this.getCharErrorDisplay(a.expecting):a instanceof org.antlr.runtime.NoViableAltException?"no viable alternative at character "+this.getCharErrorDisplay(a.c):a instanceof org.antlr.runtime.EarlyExitException?"required (...)+ loop did not match anything at character "+
this.getCharErrorDisplay(a.c):a instanceof org.antlr.runtime.MismatchedNotSetException?"mismatched character "+this.getCharErrorDisplay(a.c)+" expecting set "+a.expecting:a instanceof org.antlr.runtime.MismatchedSetException?"mismatched character "+this.getCharErrorDisplay(a.c)+" expecting set "+a.expecting:a instanceof org.antlr.runtime.MismatchedRangeException?"mismatched character "+this.getCharErrorDisplay(a.c)+" expecting set "+this.getCharErrorDisplay(a.a)+".."+this.getCharErrorDisplay(a.b):
org.antlr.runtime.Lexer.superclass.getErrorMessage.call(this,a,b)},getCharErrorDisplay:function(a){switch(a){case org.antlr.runtime.Token.EOF:a="<EOF>";break;case "\n":a="\\n";break;case "\t":a="\\t";break;case "\r":a="\\r"}return"'"+a+"'"},recover:function(){this.input.consume()},traceIn:function(a,b){var c=String.fromCharCode(this.input.LT(1))+" line="+this.getLine()+":"+this.getCharPositionInLine();org.antlr.runtime.Lexer.superclass.traceIn.call(this,a,b,c)},traceOut:function(a,b){var c=String.fromCharCode(this.input.LT(1))+
" line="+this.getLine()+":"+this.getCharPositionInLine();org.antlr.runtime.Lexer.superclass.traceOut.call(this,a,b,c)}});org.antlr.runtime.ParserRuleReturnScope=function(){};org.antlr.runtime.RuleReturnScope=function(){};org.antlr.lang.extend(org.antlr.runtime.ParserRuleReturnScope,org.antlr.runtime.RuleReturnScope,{getStart:function(){return this.start},getStop:function(){return this.stop}});org.antlr.runtime.tree.TreeRuleReturnScope=function(){};
org.antlr.lang.extend(org.antlr.runtime.tree.TreeRuleReturnScope,org.antlr.runtime.RuleReturnScope,{getStart:function(){return this.start}});org.antlr.runtime.Parser=function(a,b){org.antlr.runtime.Parser.superclass.constructor.call(this,b);this.setTokenStream(a)};
org.antlr.lang.extend(org.antlr.runtime.Parser,org.antlr.runtime.BaseRecognizer,{reset:function(){org.antlr.runtime.Parser.superclass.reset.call(this);org.antlr.lang.isValue(this.input)&&this.input.seek(0)},getCurrentInputSymbol:function(a){return a.LT(1)},getMissingSymbol:function(a,b,c){var b="<missing "+this.getTokenNames()[c]+">",c=new org.antlr.runtime.CommonToken(c,b),b=a.LT(1),d;b.getType()===org.antlr.runtime.Token.EOF&&(d=b,(b=a.LT(-1))||(b=d));c.line=b.getLine();c.charPositionInLine=b.getCharPositionInLine();
c.channel=org.antlr.runtime.BaseRecognizer.DEFAULT_TOKEN_CHANNEL;return c},setTokenStream:function(a){this.input=null;this.reset();this.input=a},getTokenStream:function(){return this.input},getSourceName:function(){return this.input.getSourceName()},traceIn:function(a,b){org.antlr.runtime.Parser.superclass.traceIn.call(this,a,b,this.input.LT(1))},traceOut:function(a,b){org.antlr.runtime.Parser.superclass.traceOut.call(this,a,b,this.input.LT(1))}});org.antlr.runtime.DFA=function(){};
org.antlr.runtime.DFA.prototype={predict:function(a){var b=a.mark(),c=0,d,e,f;try{for(;;)if(d=this.special[c],0<=d){c=this.specialStateTransition(d,a);if(-1===c)return this.noViableAlt(c,a),0;a.consume()}else{if(1<=this.accept[c])return this.accept[c];e=a.LA(1);e===org.antlr.runtime.Token.EOF?e=-1:org.antlr.lang.isString(e)&&(e=e.charCodeAt(0));if(e>=this.min[c]&&e<=this.max[c]){f=this.transition[c][e-this.min[c]];if(0>f){if(0<=this.eot[c]){c=this.eot[c];a.consume();continue}this.noViableAlt(c,a);
return 0}c=f;a.consume()}else if(0<=this.eot[c])c=this.eot[c],a.consume();else{if(e==org.antlr.runtime.Token.EOF&&0<=this.eof[c])return this.accept[this.eof[c]];this.noViableAlt(c,a);return 0}}}finally{a.rewind(b)}},noViableAlt:function(a,b){if(0<this.recognizer.state.backtracking)this.recognizer.state.failed=!0;else{var c=new org.antlr.runtime.NoViableAltException(this.getDescription(),this.decisionNumber,a,b);this.error(c);throw c;}},error:function(){},specialStateTransition:function(){return-1},
getDescription:function(){return"n/a"}};org.antlr.lang.augmentObject(org.antlr.runtime.DFA,{unpackEncodedString:function(a){var b,c=[],d=0,e,f,g;for(b=0;b<a.length;b+=2){e=a.charCodeAt(b);f=a.charCodeAt(b+1);65535===f&&(f=-1);for(g=1;g<=e;g++)c[d++]=f}return c},unpackEncodedStringToUnsignedChars:function(a){return org.antlr.runtime.DFA.unpackEncodedString(a)}});org.antlr.runtime.tree.TreeParser=function(a,b){org.antlr.runtime.tree.TreeParser.superclass.constructor.call(this,b);this.setTreeNodeStream(a)};
(function(){var a=org.antlr.runtime.tree.TreeParser;org.antlr.lang.augmentObject(a,{DOWN:org.antlr.runtime.Token.DOWN,UP:org.antlr.runtime.Token.UP});org.antlr.lang.extend(a,org.antlr.runtime.BaseRecognizer,{reset:function(){a.superclass.reset.call(this);this.input&&this.input.seek(0)},setTreeNodeStream:function(a){this.input=a},getTreeNodeStream:function(){return this.input},getSourceName:function(){return this.input.getSourceName()},getCurrentInputSymbol:function(a){return a.LT(1)},getMissingSymbol:function(a,
c,d){a="<missing "+this.getTokenNames()[d]+">";return new org.antlr.runtime.tree.CommonTree(new org.antlr.runtime.CommonToken(d,a))},matchAny:function(){this.state.errorRecovery=!1;this.state.failed=!1;var b=this.input.LT(1);if(0!==this.input.getTreeAdaptor().getChildCount(b))for(var c=0,b=this.input.getTreeAdaptor().getType(b);b!==org.antlr.runtime.Token.EOF&&!(b===a.UP&&0===c);)this.input.consume(),b=this.input.LT(1),b=this.input.getTreeAdaptor().getType(b),b===a.DOWN?c++:b===a.UP&&c--;this.input.consume()},
mismatch:function(a,c){throw new org.antlr.runtime.MismatchedTreeNodeException(c,a);},getErrorHeader:function(a){return this.getGrammarFileName()+": node from "+(a.approximateLineInfo?"after ":"")+"line "+a.line+":"+a.charPositionInLine},getErrorMessage:function(b,c){var d;this instanceof a&&(d=b.input.getTreeAdaptor(),b.token=d.getToken(b.node),org.antlr.lang.isValue(b.token)||(b.token=new org.antlr.runtime.CommonToken(d.getType(b.node),d.getText(b.node))));return a.superclass.getErrorMessage.call(this,
b,c)},traceIn:function(b,c){a.superclass.traceIn.call(this,b,c,this.input.LT(1))},traceOut:function(b,c){a.superclass.traceOut.call(this,b,c,this.input.LT(1))}})})();print=console.log;module.exports={runtime:{org:org}};
